# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Lat_long_calc
                                 A QGIS plugin
 conversion latitude/longitude between decimal degrees and DMS 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-03-11
        copyright            : (C) 2021 by Mohamed Aymen Ben Khalifa
        email                : medaymen.livee@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Lat_long_calc class from file Lat_long_calc.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .latlongcalc import Lat_long_calc
    return Lat_long_calc(iface)
